#!/usr/bin/env bash

set -e

# Hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin

echo 'Check for Homebrew and install if we don''t have it'
echo '----------------'
if test ! $(which brew); then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

echo 'Install oh-my-zsh'
echo '-----------------'
if test ! $(which omz); then
  /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/HEAD/tools/install.sh)"
  chsh -s `which zsh`

  echo 'Installing zsh plugins'
  echo '------------'
  git clone https://github.com/jessarcher/zsh-artisan.git $HOME/.oh-my-zsh/custom/plugins/artisan
  git clone https://github.com/agkozak/zsh-z  $HOME/.oh-my-zsh/custom/plugins/zsh-z

  echo 'Install zsh theme remy'
  echo '------------'
  rm $HOME/.oh-my-zsh/custom/themes/remy.zsh-theme || true
  rm $HOME/.oh-my-zsh/custom/themes/cobalt2.zsh-theme || true
  ln -s $HOME/.dotfiles/zshrc/remy.zsh-theme $HOME/.oh-my-zsh/custom/themes/remy.zsh-theme
  ln -s $HOME/.dotfiles/zshrc/cobalt2.zsh-theme $HOME/.oh-my-zsh/custom/themes/cobalt2.zsh-theme

  echo 'Activate z'
  echo '------------'
  chmod +x ~/.dotfiles/shell/z.sh
fi

echo 'Create symlinks'
echo '------------'

# Symlink zsh prefs
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc

# Symlink vim prefs
rm $HOME/.vimrc
ln -s $HOME/.dotfiles/shell/.vimrc $HOME/.vimrc
rm $HOME/.vim
ln -s $HOME/.dotfiles/shell/.vim $HOME/.vim

echo 'Setup git configs'
echo '------------'
# Add global gitignore and setup editor
rm $HOME/.global-gitignore
ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
git config --global core.excludesfile "$HOME/.global-gitignore"
git config --global include.path "$HOME/.dotfiles/config/.gitconfig"
# force default config values to be used
git config --global core.autocrlf false
git config --global core.eol native
git config --global core.editor "code --wait"
# Register git hooks
git config --global core.hooksPath $HOME/.dotfiles/git-hooks

echo 'Install brew packages'
echo '------------'

# Update Homebrew recipes
brew update

# Install all our dependencies with bundle (See Brewfile)
brew tap homebrew/bundle
brew bundle --file $HOME/.dotfiles/Brewfile

echo 'Finalize fzf install'
echo '------------'
$(brew --prefix)/opt/fzf/install

echo 'Install node version manager (nvm)'
echo '-----------'
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash

# source nvm stuff
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

nvm install 12
nvm install 14
nvm install --lts
nvm use 16

echo 'Install php environment'
echo '---------------------------'
sh $HOME/.dotfiles/install/php-env.sh

echo 'Set macOS preferences'
echo '---------------------------'
# we will run this last because this will reload the shell
source $HOME/.dotfiles/macos/set-defaults.sh

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
echo 'All done!'
echo 'Things to do to make the agnoster terminal theme work:'
echo '1. Install patched solarized theme included in ~/.dotfiles/misc/iTerm Profile.json'
echo '2. Allow sudo permittance with fingerprint. Futher instructions in ~/.dotfiles/misc/fingerprint.sh'
echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'