#!/usr/bin/env bash

set -e

# Hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin

echo 'Install homebrew'
echo '----------------'
sudo rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup  || true
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
eval "$(/opt/homebrew/bin/brew shellenv)"

echo 'Install fonts'
echo '-----------------'
brew tap homebrew/cask-fonts
brew install font-fira-code --cask

# Install zsh
echo 'Install oh-my-zsh'
echo '-----------------'
rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
chsh -s `which zsh`

echo 'Installing zsh plugins'
echo '------------'
git clone https://github.com/jessarcher/zsh-artisan.git ~/.oh-my-zsh/custom/plugins/artisan

echo 'Setup git configs'
echo '------------'

# Add global gitignore and setup editor
rm $HOME/.global-gitignore
ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
git config --global core.excludesfile "$HOME/.global-gitignore"
git config --global include.path "$HOME/.dotfiles/config/.gitconfig"
# force default config values to be used
git config --global core.autocrlf false
git config --global core.eol native
git config --global core.editor "code --wait"
# Register git hooks
git config --global core.hooksPath ~/.dotfiles/git-hooks

echo 'Create symlinks'
echo '------------'

# Symlink zsh prefs
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc

# Symlink vim prefs
rm $HOME/.vimrc
ln -s $HOME/.dotfiles/shell/.vimrc $HOME/.vimrc
rm $HOME/.vim
ln -s $HOME/.dotfiles/shell/.vim $HOME/.vim

echo 'Install zsh theme remy'
echo '------------'
rm $HOME/.oh-my-zsh/custom/themes/remy.zsh-theme || true
rm $HOME/.oh-my-zsh/custom/themes/cobalt2.zsh-theme || true
ln -s $HOME/.dotfiles/zshrc/remy.zsh-theme $HOME/.oh-my-zsh/custom/themes/remy.zsh-theme
ln -s $HOME/.dotfiles/zshrc/cobalt2.zsh-theme $HOME/.oh-my-zsh/custom/themes/cobalt2.zsh-theme

echo 'Activate z'
echo '------------'
cd ~/.dotfiles/shell
chmod +x z.sh

echo 'install z fork'
echo '------------'
git clone https://github.com/agkozak/zsh-z  $HOME/.oh-my-zsh/custom/plugins/zsh-z

echo 'Install node version manager (nvm)'
echo '-----------'
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash

# source nvm stuff
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

nvm install 12
nvm install 14
nvm install --lts
nvm use 16

echo 'Install pkg-config'
echo '------------------'
brew install pkg-config

echo 'Install wget'
echo '------------'
brew install wget

echo 'Install httpie'
echo '--------------'
brew install httpie

echo 'Install ncdu'
echo '------------'
brew install ncdu

echo 'Install hub'
echo '-----------'
brew install hub

echo 'Install ack'
echo '-----------'
brew install ack

echo 'Install tldr'
echo '-----------'
brew install tldr

echo 'Install dig'
echo '-----------'
brew install bind

echo 'Install nmap'
echo '-----------'
brew install nmap

echo 'Install fzf'
echo '-----------'
brew install fzf
$(brew --prefix)/opt/fzf/install

echo 'Install fswatch'
echo '-----------'
brew install fswatch

echo 'Install Visual Studio Code'
echo '-----------------'
brew install --cask  visual-studio-code

echo 'Install some nice quicklook plugins'
echo '-----------------------------------'
# brew  install --cask --force qlcolorcode qlstephen qlmarkdown quicklook-json qlprettypatch quicklook-csv betterzip webp-quicklook suspicious-package

echo 'Install mysql'
echo '-------------'
brew install mysql
brew services start mysql

echo 'Install redis'
echo '-------------'
brew install redis
brew services start redis

echo 'Install yarn'
echo '------------'
brew install yarn

echo 'Install ghostscript'
echo '-------------------'
brew install ghostscript

echo 'Install zsh-autosuggestions'
echo '---------------------------'
brew install zsh-autosuggestions

echo 'Install zsh-autosuggestions'
echo '---------------------------'
brew install prettyping

echo 'Install ettercap'
echo '---------------------------'
brew install ettercap

echo 'Install ffmpeg'
echo '---------------------------'
brew install ffmpeg

echo 'Install ffmpeg'
echo '---------------------------'
brew install gpg

echo 'Install php environment'
echo '---------------------------'
sh $HOME/.dotfiles/install/php-env.sh

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
echo 'All done!'
echo 'Things to do to make the agnoster terminal theme work:'
echo '1. Install menlo patched font included in ~/.dotfiles/misc https://gist.github.com/qrush/1595572/raw/Menlo-Powerline.otf'
echo '2. Install patched solarized theme included in ~/.dotfiles/misc/iTerm Profile.json'
echo '3. Allow sudo permittance with fingerprint. Futher instructions in ~/.dotfiles/misc/fingerprint.sh'

echo '++++++++++++++++++++++++++++++'
echo 'Some optional tidbits'

echo '1. Set some sensible os x defaults by running: $HOME/.dotfiles/macos/set-defaults.sh'
echo '2. Make a .dotfiles-custom/shell/.aliases for your personal commands'

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'